### ISSUE TITLE
Conduct research on WalletConnect implementation

### ISSUE THREAD

**Issue by AmmarHumackicSQA** [near-projects/wallet-selector#129]
### Description

The aim of this spike is to investigate the potential implementation of the WalletConnect protocol.

As mentioned by Mike, the WalletConnect should eventually show up as an option for the Wallet Selector. The idea is when someone chooses the WalletConnect option, the QR code is presented to the user on the website (dApp). The user then will open an app that implements a WalletConnect SDK on his mobile phone device (which has the private key).

The mobile phone scans and reads the QR code and gets two things: 
1. A private key (not attached to any blockchain, just plain vanilla cryptography key) 
2. A "relay" address. Example: https://relay-1023423.mike.stinks/ 

The frontend and the mobile phone now can communicate. They know the same private key. They could sign some message and broadcast that signed message through the relay address, which is just a websocket connection, essentially. On the receiving end, the frontend or phone app can say, that the msg is received and the message was signed by the same key "grabbed" from the QR code.

So now there is a secure communication channel established between frontend and mobile phone.

For example, the user is on some dApp, buying some tokens, or getting ready for some DeFi trade, and when they click "Submit" the payload is signed and sent through the relayer to mobile phone. The payload would be something like:  

```
{
  contract: "defi.near",
  method: "swap",
  args: ["dai", "near"]
}
```

There if the message is trusted, the transaction can be constructed, signed, and sent to the blockchain. (Or, send the bytes through the relay to the frontend, which sends it to the blockchain).

### Resources

Available WalletConnect documentation: https://docs.walletconnect.com/

https://github.com/WalletConnect

https://moralis.io/what-is-walletconnect-the-ultimate-walletconnect-guide/

**Onboard.js example:**

https://zapper.fi/

https://github.com/blocknative/onboard/blob/develop/src/modules/select/wallets/wallet-connect.ts

### Outcome

**Time Box:** 2 days

- Present findings to the team.
- Provide answers to initial questions:
  - Should we start implementing it in this stage of the project?
  - Are there any potential blockers regarding its implementation?
- Create follow-up spikes or tasks if it's determined that we should/can proceed with the WalletConnect implementation.

**Comment by kujtimprenkuSQA** [comment]
## WalletConnect findings

 - Documentation [v1.0](https://docs.walletconnect.com/)
   - [Demo](https://example.walletconnect.org/)  this is a demo app for WalletConnect version 1.0
   - [Source Code](https://github.com/WalletConnect/walletconnect-example-dapp) this is the source code for the above demo
 - Documentation [v2.0 (beta)](https://docs.walletconnect.com/2.0/)
   - [Demo](https://react-app.walletconnect.com/ ) this is a demoo app for WalletConnect 2.0
   - [Source Code](https://github.com/WalletConnect/walletconnect-monorepo/tree/v2.0/examples/react-app)  this is the source code for the above demo
 - WalletConnect official social accounts
   - Twitter account WalletConnect on [Twitter](https://twitter.com/WalletConnect)
   - WalletConnect latest news on medium WalletConnect on [Medium](https://medium.com/walletconnect) 
   
 ### Educational resources about WalletConnect

[WalletConnect: Connecting wallets to dapps](https://www.youtube.com/watch?v=PHRPoSRXPI0)
[WalletConnect 2.0 - To Interchain and Beyond!](https://www.youtube.com/watch?v=8cBIw7lFNnU)

The above videos provide answers for the below questions:

- What is WalletConnect?
- How does WalletConnect make the connection between dApps and wallets?
- What has the WalletConnect v2.0  already implemented?
- What are the future plans of WalletConnect?
- Which blockchains are already supported in WalletConnect?


### Blockchains/Wallets that have custom WalletConnect integration:

 - [Algorand](https://developer.algorand.org/docs/get-details/walletconnect/) has integrated WalletConnect in a costumized way on their ecosystem and from what I understand they have created a custom [Schema](https://developer.algorand.org/docs/get-details/walletconnect/walletconnect-schema/) for WalletConnect and also they have forked the official repo of WalletConnect and then they have published their own version of [QRModal](https://www.npmjs.com/package/algorand-walletconnect-qrcode-modal) in npm for anyone interested more about this they have a [video](https://www.youtube.com/watch?v=M5j2UQZsQNA) on youtube where they talk and explain their work so far.
 - In [COZ](https://dojo.coz.io/article/wallet_connect) they have created another [SDK](https://github.com/CityOfZion/wallet-connect-sdk) which is built on top of WalletConnect and it's for NEO Blockchain (for this one I have not yet gone through their docs and current open source repos).

## Outcome - Answers

**Should we start implementing it in this stage of the project?**

 - Based on what I have read so far there's no official news that NEAR is supported by the WalletConnect yet but it has been mentioned few times that the WalletConnect team is working on addding support for NEAR the latest news that they mention NEAR is on a post on [Medium](https://medium.com/walletconnect/walletconnect-v2-0-protocol-whats-new-3243fa80d312#:~:text=by%20Solana%20and-,Near,-.)
 - NEAR's pull request on [CAIPs](https://github.com/ChainAgnostic/CAIPs) has not been merged yet even though it has been approved by the founder of WalletConnect.
 - At this stage I think we should wait until they officially add support for NEAR.
 
**Are there any potential blockers regarding its implementation?**
 - Since I could not find any news that support for NEAR has been added to WalletConnect and the documentation for 2.0 is still in "unreleased" state I would suggest to wait at least until they announce the official support for NEAR.

**Comment by kujtimprenkuSQA** [comment]
## More info

### Stellar
After doing more research and trying to find other implementations of wallet connect found this site:
https://stellarterm.com/wallet-connect/

They have all the code of this website in  github, and here is a service where they implement the integration with WalletConnect:
https://github.com/stellarterm/stellarterm/blob/master/src/lib/driver/WalletConnectService.js

When visiting the first link if we try to login with WalletConnect a modal will be opened and you will notice the QRcode and also there's a description like: **Open your WalletConnect-compatible app with Stellar support, like LOBSTR wallet, and scan the QR code to connect.**

As I understand from what I have currently read about WalletConnect, in order for the pairing to be successful (between dApp and a Wallet)  the configuration for WalletConnect which is setup inside the dApp in our case `near-wallet-selector` when we try to create a connection(session) both the dApp and the wallet which implements WalletConnect need to know about the network of the blockchain(NEAR) in which they're trying to make the connection.

To prove this when visiting the first [link](https://stellarterm.com/wallet-connect/) and if we open the WalletConnect modal if we try to scan the QR code with any other wallet thant LOBSTR there will be no successful connection and the QRcode scanner will simply close.

### Binance

Another resource worth having a look at is [Binance docs](https://docs.binance.org/guides/concepts/walletconnect.html)  for walletconnect, there you see a **List of Wallets Supporting WalletConnect on Binance Chain** which indicates that not only the dApp needs to have support for the Binance chain but also the wallet which the dApp is trying to connect with.

**Comment by mikedotexe** [comment]
Thanks @kujtimprenkuSQA we're looking to build the integration for WalletConnect and cannot wait for another team to help. Thanks for the investigation
