### ISSUE TITLE
Signing multiple transactions with Ledger wallet

### ISSUE THREAD

**Issue by amirsaran3** [near-projects/wallet-selector#64]
Currently when signing a transaction using the Ledger Wallet option it works the first time. To sign the second time you need to logout and log back in. #23

**Comment by mikedotexe** [comment]
Is this still a problem? Wondering if the code from the MultiSafe helped, like around here:
https://github.com/multi-safe/ui.multisafe/blob/dev/src/near/LedgerSigner.js

(dev branch)

**Comment by amirsaran3** [comment]
I found a weird bug when signing transactions.

I create a transaction with message "1111". Sign it, approve it with ledger. I create another transaction with message "2222". When I try to sign it, on my physical device on the screen I see the arguments from the previous transaction ("1111").

This means that for the second transactions it still using the old buffer data.

I checked the buffer string that I am sending to the Ledger device with APDU logging (using this package `@ledgerhq/logs`) and it has the "2222" message. But still on the screen of the device when approving transaction I see the "1111" message.

This is a possible bug that is causing the error which doesn't let us add messages twice in a row.
```
Uncaught (in promise) Error: Transaction is not signed with the given public key
    at Object.parseRpcError (rpc_errors.js:24:1)
    at json-rpc-provider.js:319:44
    at async Object.exponentialBackoff [as default] (exponential-backoff.js:7:1)
    at async JsonRpcProvider.sendJsonRpc (json-rpc-provider.js:304:26)
```

**Comment by lewis-sqa** [comment]
After some further investigation into this bug, I believe the crux of the problem is we aren't fetching the most recent nonce right before signing. We're currently fetching the once initially and incrementing thereafter. I'm not completely knowledgeable about how nonce tokens work, but in my head the blockchain(?) has moved on by the time we try to sign the next transaction. 

The Multi Safe project referenced above doesn't provide examples of using `sendMessage`. However, the link to `near-ledger-js` was helpful for getting my head around Ledger and how our implementation has come to be 🙂
