### ISSUE TITLE
As a dApp user, I WANT to be able to choose the option "connect with Narwallet" from the modal SO THAT Narwallet browser extension window pops up AND so that I can approve the connection between my Narwallet account and dApp

### ISSUE THREAD

**Issue by AmmarHumackicSQA** [near-projects/wallet-selector#8]

**Comment by AmmarHumackicSQA** [comment]
# Acceptance criteria

GIVEN that I access dApp
WHEN I choose "connect with Narwallet" option from the modal
THEN Narwallet browser extension window pops up 
AND I can approve the connection between my Narwallet account and dApp                                                                                  
AND my wallet account is connected after approval

**Comment by lewis-sqa** [comment]
Due to the [design of Narwallet](https://github.com/Narwallets/narwallets-extension/blob/master/API-design.md#design), we're unable to integrate with this wallet. This is because the wallet connects with the dApp, instead of the more common approach in which the dApp establishes the connection with the wallet.
